- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: dnf install nginx -y 
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: denable
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    

      