- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: dnf install nginx -y 
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: enable
    ansible.builtin.system:
      name: nginx
      state: started
      enabled: yes      



  - name: rm -rf /usr/share/nginx/html/*
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent    

      